// Elite Auto Gallery - Main JavaScript

class EliteAutoGallery {
  constructor() {
    this.cars = [];
    this.filteredCars = [];
    this.init();
  }

  async init() {
    await this.loadCars();
    this.setupEventListeners();
    this.renderCars();
  }

  async loadCars() {
    try {
      // Load cars from the _cars folder (generated by Decap CMS)
      const response = await fetch('/admin/cars.json');
      if (response.ok) {
        const data = await response.json();
        this.cars = data.cars || [];
      } else {
        // Fallback to sample data if no CMS data exists yet
        this.cars = this.getSampleCars();
      }
      this.filteredCars = this.cars.filter(car => car.status === 'Available');
    } catch (error) {
      console.log('Loading sample data...');
      this.cars = this.getSampleCars();
      this.filteredCars = this.cars.filter(car => car.status === 'Available');
    }
  }

  getSampleCars() {
    return [
      {
        id: '1',
        make: 'BMW',
        model: '3 Series',
        year: 2022,
        price: 38500,
        mileage: 25000,
        fuel_type: 'Gasoline',
        transmission: 'Automatic',
        body_type: 'Sedan',
        color: 'Alpine White',
        image_url: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80',
        description: 'Stunning BMW 3 Series in pristine condition. Features include leather interior, navigation system, and premium sound system. Low mileage and well-maintained.',
        features: ['Leather Seats', 'Navigation', 'Sunroof', 'Backup Camera', 'Bluetooth', 'Sport Package', 'Heated Seats'],
        status: 'Available',
        is_featured: true
      },
      {
        id: '2',
        make: 'Mercedes-Benz',
        model: 'E-Class',
        year: 2021,
        price: 45900,
        mileage: 32000,
        fuel_type: 'Gasoline',
        transmission: 'Automatic',
        body_type: 'Sedan',
        color: 'Selenite Grey',
        image_url: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80',
        description: 'Elegant Mercedes-Benz E-Class with premium features and excellent condition. AMG line with performance exhaust.',
        features: ['AMG Line', 'Premium Sound', 'Heated Seats', 'Lane Assist', 'Cruise Control', 'Panoramic Roof'],
        status: 'Available',
        is_featured: true
      },
      {
        id: '3',
        make: 'Porsche',
        model: 'Cayenne',
        year: 2023,
        price: 72000,
        mileage: 12000,
        fuel_type: 'Hybrid',
        transmission: 'Automatic',
        body_type: 'SUV',
        color: 'Black',
        image_url: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&q=80',
        description: 'Luxurious Porsche Cayenne with hybrid powertrain. Nearly new with full manufacturer warranty remaining.',
        features: ['Sport Package', 'Panoramic Roof', 'Air Suspension', 'Premium Audio', 'Carbon Ceramic Brakes', '22" Wheels'],
        status: 'Available',
        is_featured: true
      },
      {
        id: '4',
        make: 'Audi',
        model: 'A4',
        year: 2022,
        price: 35500,
        mileage: 28000,
        fuel_type: 'Gasoline',
        transmission: 'Automatic',
        body_type: 'Sedan',
        color: 'Glacier White',
        image_url: 'https://images.unsplash.com/photo-1606220838315-056192d5e927?w=800&q=80',
        description: 'Well-maintained Audi A4 with full service history. Quattro all-wheel drive for superior handling.',
        features: ['Quattro AWD', 'Virtual Cockpit', 'LED Headlights', 'Apple CarPlay', 'Parking Sensors', 'Cruise Control'],
        status: 'Available',
        is_featured: false
      },
      {
        id: '5',
        make: 'Tesla',
        model: 'Model 3',
        year: 2023,
        price: 42000,
        mileage: 8000,
        fuel_type: 'Electric',
        transmission: 'Automatic',
        body_type: 'Sedan',
        color: 'Pearl White',
        image_url: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&q=80',
        description: 'Like-new Tesla Model 3 Long Range with Autopilot. Low mileage and comprehensive warranty coverage.',
        features: ['Autopilot', 'Premium Sound', 'Glass Roof', 'Supercharging', '19" Wheels', 'White Interior'],
        status: 'Available',
        is_featured: true
      },
      {
        id: '6',
        make: 'Lexus',
        model: 'RX 350',
        year: 2021,
        price: 48500,
        mileage: 35000,
        fuel_type: 'Gasoline',
        transmission: 'Automatic',
        body_type: 'SUV',
        color: 'Atomic Silver',
        image_url: 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800&q=80',
        description: 'Premium Lexus RX 350 with F Sport package. Immaculate condition with full dealer service history.',
        features: ['F Sport Package', 'Mark Levinson Audio', 'Heads-Up Display', 'Adaptive Cruise', 'Heated & Cooled Seats', '360 Camera'],
        status: 'Available',
        is_featured: false
      }
    ];
  }

  setupEventListeners() {
    // Mobile menu toggle
    const mobileMenuBtn = document.getElementById('mobile-menu-btn');
    const mobileMenu = document.getElementById('mobile-menu');
    if (mobileMenuBtn && mobileMenu) {
      mobileMenuBtn.addEventListener('click', () => {
        mobileMenu.classList.toggle('active');
      });
    }

    // Search and filter functionality
    const searchInput = document.getElementById('search');
    const bodyTypeFilter = document.getElementById('body-type');
    const fuelTypeFilter = document.getElementById('fuel-type');
    const transmissionFilter = document.getElementById('transmission');

    if (searchInput) {
      searchInput.addEventListener('input', () => this.applyFilters());
    }
    if (bodyTypeFilter) {
      bodyTypeFilter.addEventListener('change', () => this.applyFilters());
    }
    if (fuelTypeFilter) {
      fuelTypeFilter.addEventListener('change', () => this.applyFilters());
    }
    if (transmissionFilter) {
      transmissionFilter.addEventListener('change', () => this.applyFilters());
    }
  }

  applyFilters() {
    const searchTerm = document.getElementById('search')?.value.toLowerCase() || '';
    const bodyType = document.getElementById('body-type')?.value || 'all';
    const fuelType = document.getElementById('fuel-type')?.value || 'all';
    const transmission = document.getElementById('transmission')?.value || 'all';

    this.filteredCars = this.cars.filter(car => {
      if (car.status !== 'Available') return false;

      const matchesSearch = !searchTerm ||
        `${car.make} ${car.model} ${car.year}`.toLowerCase().includes(searchTerm);
      const matchesBody = bodyType === 'all' || car.body_type === bodyType;
      const matchesFuel = fuelType === 'all' || car.fuel_type === fuelType;
      const matchesTrans = transmission === 'all' || car.transmission === transmission;

      return matchesSearch && matchesBody && matchesFuel && matchesTrans;
    });

    this.renderCars();
  }

  renderCars() {
    const carGrid = document.getElementById('car-grid');
    const resultsCount = document.getElementById('results-count');

    if (resultsCount) {
      resultsCount.textContent = `${this.filteredCars.length} vehicle${this.filteredCars.length !== 1 ? 's' : ''} found`;
    }

    if (!carGrid) return;

    if (this.filteredCars.length === 0) {
      carGrid.innerHTML = '<div class="col-span-full text-center py-20"><p class="text-slate-500">No vehicles found matching your criteria.</p></div>';
      return;
    }

    carGrid.innerHTML = this.filteredCars.map(car => this.createCarCard(car)).join('');
  }

  createCarCard(car) {
    return `
      <a href="car-details.html?id=${car.id}" class="car-card">
        <div class="car-image">
          <img src="${car.image_url || 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80'}" 
               alt="${car.year} ${car.make} ${car.model}">
          <span class="badge">${car.status || 'Available'}</span>
          ${car.is_featured ? '<span class="badge featured">Featured</span>' : ''}
        </div>
        <div class="car-content">
          <div class="car-header">
            <div>
              <h3 class="car-title">${car.year} ${car.make} ${car.model}</h3>
              <p class="car-body-type">${car.body_type}</p>
            </div>
            <p class="car-price">$${car.price?.toLocaleString()}</p>
          </div>
          <div class="car-specs">
            <div class="car-spec">
              <svg class="icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/>
              </svg>
              <span>${car.mileage?.toLocaleString()} mi</span>
            </div>
            <div class="car-spec">
              <svg class="icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/>
              </svg>
              <span>${car.fuel_type}</span>
            </div>
            <div class="car-spec">
              <svg class="icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"/>
              </svg>
              <span>${car.year}</span>
            </div>
          </div>
          <div class="view-details">
            View Details
            <svg class="icon-sm" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/>
            </svg>
          </div>
        </div>
      </a>
    `;
  }

  renderFeaturedCars() {
    const featuredGrid = document.getElementById('featured-cars');
    if (!featuredGrid) return;

    const featured = this.cars.filter(car => car.is_featured && car.status === 'Available').slice(0, 3);

    if (featured.length === 0) {
      // Show first 3 available cars if no featured ones
      const available = this.cars.filter(car => car.status === 'Available').slice(0, 3);
      if (available.length > 0) {
        featuredGrid.innerHTML = available.map(car => this.createCarCard(car)).join('');
      } else {
        featuredGrid.innerHTML = '<p class="text-center text-slate-500" style="grid-column: 1/-1;">No featured vehicles available.</p>';
      }
      return;
    }

    featuredGrid.innerHTML = featured.map(car => this.createCarCard(car)).join('');
  }

  async loadCarDetails() {
    const urlParams = new URLSearchParams(window.location.search);
    const carId = urlParams.get('id');

    if (!carId) {
      this.showError('Car not found');
      return;
    }

    await this.loadCars();
    const car = this.cars.find(c => c.id === carId);

    if (!car) {
      this.showError('Car not found');
      return;
    }

    this.renderCarDetails(car);
  }

  renderCarDetails(car) {
    document.title = `${car.year} ${car.make} ${car.model} - Elite Auto Gallery`;

    const container = document.getElementById('car-details-container');
    if (!container) return;

    container.innerHTML = `
      <a href="gallery.html" class="back-button animate-slide-left">
        <svg class="icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"/>
        </svg>
        Back to Gallery
      </a>

      <div class="car-detail-grid">
        <div class="car-detail-image animate-slide-left delay-100">
          <img src="${car.image_url || 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80'}" 
               alt="${car.year} ${car.make} ${car.model}">
          <span class="badge">${car.status || 'Available'}</span>
        </div>

        <div>
          <div class="info-box animate-slide-right delay-200">
            <h1>${car.year} ${car.make} ${car.model}</h1>
            <p class="price">$${car.price?.toLocaleString()}</p>

            <ul class="spec-list">
              <li class="spec-item">
                <span class="spec-label">
                  <svg class="icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"/>
                  </svg>
                  Year
                </span>
                <span class="spec-value">${car.year}</span>
              </li>
              <li class="spec-item">
                <span class="spec-label">
                  <svg class="icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/>
                  </svg>
                  Mileage
                </span>
                <span class="spec-value">${car.mileage?.toLocaleString()} mi</span>
              </li>
              <li class="spec-item">
                <span class="spec-label">
                  <svg class="icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/>
                  </svg>
                  Fuel Type
                </span>
                <span class="spec-value">${car.fuel_type || '-'}</span>
              </li>
              <li class="spec-item">
                <span class="spec-label">
                  <svg class="icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"/>
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/>
                  </svg>
                  Transmission
                </span>
                <span class="spec-value">${car.transmission || '-'}</span>
              </li>
              <li class="spec-item">
                <span class="spec-label">
                  <svg class="icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 21a4 4 0 01-4-4V5a2 2 0 012-2h4a2 2 0 012 2v12a4 4 0 01-4 4zm0 0h12a2 2 0 002-2v-4a2 2 0 00-2-2h-2.343M11 7.343l1.657-1.657a2 2 0 012.828 0l2.829 2.829a2 2 0 010 2.828l-8.486 8.485M7 17h.01"/>
                  </svg>
                  Color
                </span>
                <span class="spec-value">${car.color || '-'}</span>
              </li>
              <li class="spec-item">
                <span class="spec-label">
                  <svg class="icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4"/>
                  </svg>
                  Body Type
                </span>
                <span class="spec-value">${car.body_type || '-'}</span>
              </li>
            </ul>
          </div>

          ${car.description ? `
            <div class="info-box description-box animate-slide-right delay-300">
              <h2>Description</h2>
              <p>${car.description}</p>
            </div>
          ` : ''}

          ${car.features && car.features.length > 0 ? `
            <div class="info-box features-box animate-slide-right delay-400">
              <h2>Features</h2>
              <div class="feature-tags">
                ${car.features.map(feature => `<span class="feature-tag">${feature}</span>`).join('')}
              </div>
            </div>
          ` : ''}

          <div class="contact-cta animate-slide-right delay-500">
            <h3>Interested in this vehicle?</h3>
            <p>Contact us today to schedule a test drive or get more information.</p>
            <div class="contact-buttons">
              <a href="contact.html?car=${car.id}" class="btn">
                <svg class="icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"/>
                </svg>
                Send Inquiry
              </a>
              <a href="tel:07918931399" class="btn">
                <svg class="icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z"/>
                </svg>
                07918 931399
              </a>
            </div>
          </div>
        </div>
      </div>
    `;
  }

  showError(message) {
    const container = document.getElementById('car-details-container');
    if (container) {
      container.innerHTML = `
        <div style="text-align: center; padding: 4rem 0;">
          <p style="color: var(--slate-500); margin-bottom: 1rem;">${message}</p>
          <a href="gallery.html" class="btn">Back to Gallery</a>
        </div>
      `;
    }
  }
}

// Initialize the app
document.addEventListener('DOMContentLoaded', () => {
  const app = new EliteAutoGallery();

  // Check which page we're on and render accordingly
  if (document.getElementById('car-grid')) {
    // Gallery page
    app.renderCars();
  } else if (document.getElementById('featured-cars')) {
    // Home page
    app.renderFeaturedCars();
  } else if (document.getElementById('car-details-container')) {
    // Car details page
    app.loadCarDetails();
  }
});
